version: '3.7'

services:
  # mysql
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./data/:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=test"
      - "MYSQL_DATABASE=test"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test"
